name: playground
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative-Regular.ttf
        - asset: assets/fonts/SignikaNegative-SemiBold.ttf
        - asset: assets/fonts/SignikaNegative-Bold.ttf
